services:
  memo_api:
    container_name: memo_api
    image: ${DOCKERHUB_USERNAME}/memo_api:${TAG:-latest}
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_HOST=${PINECONE_HOST}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
    volumes:
      - ./api_data:/app
    labels:
      - "prometheus.scrape=true"
      - "prometheus.app=memo_api"
      - "prometheus.port=8000"
    networks:
      - logging

  memo_tg:
    container_name: memo_tg
    image: ${DOCKERHUB_USERNAME}/memo_tg:${TAG:-latest}
    restart: unless-stopped
    environment:
      - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}
      - API_BASE_URL=http://memo_api:8000
    volumes:
      - ./tg_data:/app
    depends_on:
      - memo_api
    labels:
      - "prometheus.scrape=true"
      - "prometheus.app=memo_tg"
      - "prometheus.port=8000"
    networks:
      - logging

networks:
  logging:
    external: true
    name: logging_network