name: Lint and Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_call:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync

      - name: Run Ruff linter
        run: uvx ruff check .

      - name: Run Tests
        run: uv run pytest
        env:
          OPENAI_API_KEY: "secret"
          PINECONE_API_KEY: "secret"
          PINECONE_HOST: "secret"
          CLAUDE_API_KEY: "secret"
          DATA_FOLDER: "."
